### ISSUE TITLE
Support S3 and others

### ISSUE THREAD

**Issue by jdonnerstag** [hunger/downloader#5]
## Problem

Would it be difficult to add support for downloads from S3, Google cloud storage and possibly others?

**Comment by hunger** [comment]
I thought those services use standard HTTP downloads.

What would you like to see implemented here?

**Comment by hunger** [comment]
Please feel free to re-open if you can provide some use-cases you would like to see covered.

Without some use-cases I do not know what I can do with this issue, so I can just as well close it.
