### ISSUE TITLE
Compilation error with `tui` feature enabled.

### ISSUE THREAD

**Issue by citizen-stig** [hunger/downloader#60]
If I run `cargo clippy --all-targets --all-features` getting this error:

```
error[E0599]: no method named `join` found for struct `indicatif::MultiProgress` in the current scope
   --> src/progress.rs:107:18
    |
106 | /             self.progress_group
107 | |                 .join()
    | |                 -^^^^ method not found in `MultiProgress`
    | |_________________|
    |
    |
    = help: items from traits can only be used if the trait is implemented and in scope
note: `progress::Factory` defines an item `join`, perhaps you need to implement it
```

I dig a little bit and it looks like this method has been removed https://github.com/console-rs/indicatif/pull/284

I am happy to help with this, but it looks like this change will require significant change in how ProgressBar is built for Tui

**Comment by hunger** [comment]
I have long since stopped using this crate, I do not plan to spend time on it soon:-) Feel free to upgrade it :-)
