### ISSUE TITLE
Is it possible to release new version, 0.2.8

### ISSUE THREAD

**Issue by citizen-stig** [hunger/downloader#61]
Since https://github.com/hunger/downloader/pull/59 has been merged, it will significantly help removing reqwest 0.11 from depedency tree of many projects

**Comment by hunger** [comment]
I'll see what I can do over the WE :-) I can't promise anything though.

**Comment by citizen-stig** [comment]
Thanks a lot anyway!

**Comment by hunger** [comment]
Done, it's up on crates.io.
