### ISSUE TITLE
ability to get size of files for downloading

### ISSUE THREAD

**Issue by bobi6666** [hunger/downloader#9]
hello another feature I would like to ask you is the ability to see the file size of the file that is currently being downloaded so that I can show it to the players who are downloading files in my game

**Comment by hunger** [comment]
The file length should actually be set on the progress reporter here:

https://github.com/hunger/downloader/blob/dceb1eb18216590f7b6ce4f8d4c8de4582d2ef72/src/backend.rs#L30

-- if that was reported by the server.

**Comment by bobi6666** [comment]
this proges let me ttrack current downloaded bytes and total file size?

2021-11-22 9:19 GMT+01:00, Tobias Hunger ***@***.***>:

**Comment by hunger** [comment]
Max_progress should be set to the total file size in bytes (if that is known) and then the progress is set to the number of bytes downloaded.

So in theory this should do what you are asking for:-)
